language: java
jdk:
  - oraclejdk8

install: ant
script: ant test

notifications:
 email:
    recipients:
      - delmazofederico@gmail.com
      - nraveszani@gmail.com
      - viky_zambi95@hotmail.com
      - florrr1997@gmail.com
    on_failure: always
    on_success: always